/**
 * TypeScript Type Definitions for IGotYou Frontend
 * 
 * This file defines all the data types used throughout the frontend.
 * These types match the Pydantic models in the backend.
 * 
 * IMPORTANT: Keep these in sync with backend/main.py models!
 */


// ============================================================================
// REQUEST TYPES
// ============================================================================

/**
 * Request payload for discovering hidden gems
 * 
 * @example
 * const query: DiscoveryQuery = {
 *   searchQuery: "quiet beaches in California"
 * };
 */
export interface DiscoveryQuery {
  searchQuery: string;
}


// ============================================================================
// LOCATION TYPES
// ============================================================================

/**
 * Geographic coordinates for mapping
 * 
 * @example
 * const coords: Coordinates = { lat: 37.7749, lng: -122.4194 };
 */
export interface Coordinates {
  lat: number;
  lng: number;
}


// ============================================================================
// NEW: WEATHER TYPES (MCP Integration)
// ============================================================================

/**
 * Weather data from MCP weather server (AccuWeather)
 * 
 * This data is fetched via the MCP protocol from AccuWeather
 * and provides current conditions for each hidden gem location.
 * 
 * @example
 * const weather: Weather = {
 *   temperature: 72,
 *   conditions: "Partly Cloudy",
 *   humidity: 55,
 *   hasPrecipitation: false
 * };
 */
export interface Weather {
  /** Current temperature in Fahrenheit (null if unavailable) */
  temperature: number | null;
  
  /** Weather description (e.g., "Sunny", "Rainy", "Weather unavailable") */
  conditions: string;
  
  /** Humidity percentage 0-100 (null if unavailable) */
  humidity: number | null;
  
  /** Whether precipitation (rain/snow) is occurring */
  hasPrecipitation: boolean;
}


// ============================================================================
// ANALYSIS TYPES (Updated with clothing recommendation)
// ============================================================================

/**
 * AI-generated analysis and insights for a hidden gem
 * 
 * Generated by the Recommendation Agent based on user reviews,
 * with clothing recommendations added by the Weather Agent.
 * 
 * @example
 * const analysis: Analysis = {
 *   whySpecial: "This secluded beach is known for its calm waters...",
 *   bestTime: "Early morning for the best sunrise views",
 *   insiderTip: "Bring your own shade - there's no tree cover",
 *   clothingRecommendation: "Wear light, breathable clothing and bring sunscreen"
 * };
 */
export interface Analysis {
  /** 2-3 sentences explaining why this is a hidden gem */
  whySpecial: string;
  
  /** Best time to visit for optimal experience */
  bestTime: string;
  
  /** Practical insider tip from reviews */
  insiderTip: string;
  
  /** NEW: AI-generated clothing recommendation based on weather */
  clothingRecommendation?: string;
}


// ============================================================================
// HIDDEN GEM TYPES (Updated with weather field)
// ============================================================================

/**
 * A discovered hidden gem with all its details
 * 
 * This is the main data type returned by the agent pipeline.
 * Includes location info, photos, AI analysis, and weather data.
 * 
 * @example
 * const gem: HiddenGem = {
 *   placeName: "Secret Beach",
 *   address: "123 Ocean Dr, Malibu, CA",
 *   coordinates: { lat: 34.0259, lng: -118.7798 },
 *   rating: 4.5,
 *   reviewCount: 87,
 *   photos: ["https://..."],
 *   analysis: { ... },
 *   weather: { temperature: 72, conditions: "Sunny", ... }
 * };
 */
export interface HiddenGem {
  /** Name of the place */
  placeName: string;
  
  /** Full street address */
  address: string;
  
  /** Geographic coordinates for mapping */
  coordinates: Coordinates;
  
  /** Google rating (0-5 stars) */
  rating: number;
  
  /** Number of Google reviews */
  reviewCount: number;
  
  /** Array of photo URLs */
  photos: string[];
  
  /** AI-generated analysis and insights */
  analysis: Analysis;
  
  /** NEW: Current weather conditions (optional - may be unavailable) */
  weather?: Weather;
}


// ============================================================================
// RESPONSE TYPES
// ============================================================================

/**
 * Response from the /api/discover endpoint
 * 
 * Contains the discovered gems along with metadata about the request.
 * 
 * @example
 * const response: DiscoveryResponse = {
 *   gems: [...],
 *   processingTime: 12.5,
 *   query: "quiet beaches in California"
 * };
 */
export interface DiscoveryResponse {
  /** Array of discovered hidden gems */
  gems: HiddenGem[];
  
  /** How long the request took (in seconds) */
  processingTime: number;
  
  /** The original search query */
  query: string;
}
